### ISSUE TITLE
平面内旋转人脸检测

### ISSUE THREAD

**Issue by seeyourcell** [OAID/YSQfastfd#1]
hi，ysq的方法能极爱你测平面内旋转的人脸吗？ roll 转动

**Comment by xhbdahai** [comment]
需要支持旋转多少度？

**Comment by seeyourcell** [comment]
期望-180°~+180°
ysq的方法roll方向最大角度有多少？
不能达到-180°~+180°，只能对图像整体旋转，再去检测。

**Comment by xhbdahai** [comment]
确认了，不支持。
