### ISSUE TITLE
detection failed after several minutes

### ISSUE THREAD

**Issue by GarrickLin** [OAID/YSQfastfd#2]
I ran the code in rk3288 successfully. But after several minutes I found it failed detecting faces. Is this inherent or just a bug ?

**Comment by chezhqant** [comment]
Hi, i have a rk3288, my board's system is "Firefly-rk3288_Ubuntu_1604_201705250940.img".and when i input "make -j4", i got failed. and the fault information is "libysqfd64.so: file not recognized: File format not recognized ". could you help me ? please.

**Comment by GarrickLin** [comment]
just comment [this line](https://github.com/OAID/YSQfastfd/blob/master/makefile.mk#L6) to build a 32bit target.

**Comment by xhbdahai** [comment]
@GarrickLin , Yes, it is inherent. The evaluation version only support 2000 frames detection.

**Comment by xhbdahai** [comment]
@chezhai please show me the detailed log information if possible.

**Comment by chezhqant** [comment]
Thanks, GarrickLin  has sovled my question. @xhbdahai

**Comment by waveajay** [comment]
@xhbdahai from where I can get full version
