### ISSUE TITLE
/usr/bin/ld: cannot find -lysqfd64

### ISSUE THREAD

**Issue by albertmf** [OAID/YSQfastfd#5]
When i  make fddemo, i have this problem, how can i solve it?

make[1]: Entering directory '/mnt/hgfs/YSQfastfd/trunk/fddemo'
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/mnt/hgfs/YSQfastfd/trunk/include -DPERF_STATISTICS -D__linux__ ysqfddemo.c -o ysqfddemo -lm -lpthread `pkg-config --libs gtk+-3.0` -L/mnt/hgfs/YSQfastfd/trunk/libfcv -loal -L/mnt/hgfs/YSQfastfd/trunk/middle -laaid -L/mnt/hgfs/YSQfastfd/trunk/3rdlibs -lysqfd64 -lm -lpthread `pkg-config --libs gtk+-3.0`
/usr/bin/ld: skipping incompatible /mnt/hgfs/YSQfastfd/trunk/3rdlibs/libysqfd64.so when searching for -lysqfd64
/usr/bin/ld: cannot find -lysqfd64
collect2: error: ld returned 1 exit status
Makefile:13: recipe for target 'ysqfddemo' failed
make[1]: *** [ysqfddemo] Error 1
make[1]: Leaving directory '/mnt/hgfs/YSQfastfd/trunk/fddemo'
Makefile:21: recipe for target 'apps' failed
make: *** [apps] Error 2

**Comment by xhbdahai** [comment]
@albertmf  Please run "uname -a" in shell command line to check your machine type first. libysqfd64 is working on ARM64, if try to on ARM32. You need comment "ONARM64 = 1"  or set "ONARM64 = 0" in makefile.mk

**Comment by albertmf** [comment]
直接用中文问了哈！我是在虚拟机上编译的，安装了gcc-linaro-aarch64-linux-gnu的交叉编译工具链，但是在后面ld的时候还是报错了，log如下/opt/gcc-linaro-aarch64-linux-gnu-4.9-2014.07_linux/bin/../lib/gcc/aarch64-linux-gnu/4.9.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lgtk-3
等好几个库都链接不到，是不是我虚拟机上的库不对（虚拟机的平台是x86-64的）？
还是说我得在我需要执行的平台上安装相应的工具链和库然后编译？

**Comment by xhbdahai** [comment]
@albertmf 目前不支持交叉编译环境。直接在本地编译。

**Comment by wait1988** [comment]
@xhbdahai 
uname -a:
Linux sunqin-pc 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
同样遇到这个问题
/usr/bin/ld: 当搜索用于 /home/sunqin/deep_learning/YSQfastfd/3rdlibs/libysqfd64.so 时跳过不兼容的 -lysqfd64
/usr/bin/ld: 找不到 -lysqfd64
换成32也不行

**Comment by Minotaur-CN** [comment]
linux下和andorid可以使用么？

**Comment by jia0511** [comment]
@xhbdahai
/usr/bin/ld: 当搜索用于 /home/sunqin/deep_learning/YSQfastfd/3rdlibs/libysqfd64.so 时跳过不兼容的 -lysqfd64
/usr/bin/ld: 找不到 -lysqfd64
楼主 请问同样问题，如何解决？ 我想在Linux下运行。

**Comment by xhbdahai** [comment]
@jia0511 完整的错误信息给我看看。同时提供一下“uname -a”输出

**Comment by lfywork** [comment]
Hi! I have the same problem when I compiled the project "YSQfastfd-GCC-version".
The log is below:
make[1]: Entering directory '/home/fangyu/code/YSQfastfd-GCC-version/libfcv'
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/fangyu/code/YSQfastfd-GCC-version/include -DPERF_STATISTICS -D__linux__ -c video.c -o video.o
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/fangyu/code/YSQfastfd-GCC-version/include -DPERF_STATISTICS -D__linux__ -c yuvproc.c -o yuvproc.o
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/fangyu/code/YSQfastfd-GCC-version/include -DPERF_STATISTICS -D__linux__ -c window.c -o window.o
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/fangyu/code/YSQfastfd-GCC-version/include -DPERF_STATISTICS -D__linux__ -c fcvimage.c -o fcvimage.o
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/fangyu/code/YSQfastfd-GCC-version/include -DPERF_STATISTICS -D__linux__ -c queue.c -o queue.o
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/fangyu/code/YSQfastfd-GCC-version/include -DPERF_STATISTICS -D__linux__ -c aaidsys.c -o aaidsys.o
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/fangyu/code/YSQfastfd-GCC-version/include -DPERF_STATISTICS -D__linux__ -c ysqfd.c -o ysqfd.o
ar -rcv liboal.a video.o yuvproc.o window.o fcvimage.o queue.o aaidsys.o ysqfd.o
a - video.o
a - yuvproc.o
a - window.o
a - fcvimage.o
a - queue.o
a - aaidsys.o
a - ysqfd.o
make[1]: Leaving directory '/home/fangyu/code/YSQfastfd-GCC-version/libfcv'
make[1]: Entering directory '/home/fangyu/code/YSQfastfd-GCC-version/middle'
g++ -fpic -shared -DCAM_FRAME_480P -Wall -O2 -I/home/fangyu/code/YSQfastfd-GCC-version/include -DPERF_STATISTICS -D_linux__ -c midlayer.cpp -o midlayer.o
g++ -fpic -shared -DCAM_FRAME_480P -Wall -O2 -I/home/fangyu/code/YSQfastfd-GCC-version/include -DPERF_STATISTICS -D_linux__ -o libaaid.so midlayer.o
make[1]: Leaving directory '/home/fangyu/code/YSQfastfd-GCC-version/middle'
make[1]: Entering directory '/home/fangyu/code/YSQfastfd-GCC-version/fcvlibtest'
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/fangyu/code/YSQfastfd-GCC-version/include -DPERF_STATISTICS -D__linux__ libfcvtest.c -o libfcvtest -lm -lpthread `pkg-config --libs gtk+-3.0` -L/home/fangyu/code/YSQfastfd-GCC-version/libfcv -loal -lm -lpthread `pkg-config --libs gtk+-3.0`
make[1]: Leaving directory '/home/fangyu/code/YSQfastfd-GCC-version/fcvlibtest'
make[1]: Entering directory '/home/fangyu/code/YSQfastfd-GCC-version/fddemo'
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/fangyu/code/YSQfastfd-GCC-version/include -DPERF_STATISTICS -D__linux__ ysqfddemo.c -o ysqfddemo -lm -lpthread `pkg-config --libs gtk+-3.0` -L/home/fangyu/code/YSQfastfd-GCC-version/libfcv -loal -L/home/fangyu/code/YSQfastfd-GCC-version/middle -laaid -L/home/fangyu/code/YSQfastfd-GCC-version/3rdlibs -lysqfd64 -lm -lpthread `pkg-config --libs gtk+-3.0`
/usr/bin/ld: skipping incompatible /home/fangyu/code/YSQfastfd-GCC-version/3rdlibs/libysqfd64.so when searching for -lysqfd64
/usr/bin/ld: cannot find -lysqfd64
collect2: error: ld returned 1 exit status
Makefile:13: recipe for target 'ysqfddemo' failed
make[1]: *** [ysqfddemo] Error 1
make[1]: Leaving directory '/home/fangyu/code/YSQfastfd-GCC-version/fddemo'
Makefile:21: recipe for target 'apps' failed
make: *** [apps] Error 2


I try to resolve the problem by myself. I can find a file which name is "libysqfd64.so" under 3rdlibs by file system.Why cannot find?

uname -a:
fangyu@thinkpad-e560:~/code/YSQfastfd-GCC-version$ uname -a
Linux thinkpad-e560 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

regard for your answer
