### ISSUE TITLE
make -j4编译测试这个YSQfastfd时遇到问题

### ISSUE THREAD

**Issue by liugang27** [OAID/YSQfastfd#8]
make -j4编译测试这个YSQfastfd时遇到问题
`
arthur@ubuntu:/home/share/YSQfastfd$ make -j4
make[1]: Entering directory `/home/share/YSQfastfd/libfcv'
make[1]: Leaving directory `/home/share/YSQfastfd/libfcv'
make[1]: Entering directory `/home/share/YSQfastfd/libfcv'
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/share/YSQfastfd/include -DPERF_STATISTICS -D__linux__ -c video.c -o video.o
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/share/YSQfastfd/include -DPERF_STATISTICS -D__linux__ -c yuvproc.c -o yuvproc.o
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/share/YSQfastfd/include -DPERF_STATISTICS -D__linux__ -c window.c -o window.o
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/share/YSQfastfd/include -DPERF_STATISTICS -D__linux__ -c fcvimage.c -o fcvimage.o
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/share/YSQfastfd/include -DPERF_STATISTICS -D__linux__ -c queue.c -o queue.o
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/share/YSQfastfd/include -DPERF_STATISTICS -D__linux__ -c aaidsys.c -o aaidsys.o
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/share/YSQfastfd/include -DPERF_STATISTICS -D__linux__ -c ysqfd.c -o ysqfd.o
ar -rcv liboal.a video.o yuvproc.o window.o fcvimage.o queue.o aaidsys.o ysqfd.o
a - video.o
a - yuvproc.o
a - window.o
a - fcvimage.o
a - queue.o
a - aaidsys.o
a - ysqfd.o
make[1]: Leaving directory `/home/share/YSQfastfd/libfcv'
make[1]: Entering directory `/home/share/YSQfastfd/middle'
make[1]: Leaving directory `/home/share/YSQfastfd/middle'
make[1]: Entering directory `/home/share/YSQfastfd/middle'
g++ -fpic -shared -DCAM_FRAME_480P -Wall -O2 -I/home/share/YSQfastfd/include -DPERF_STATISTICS -D_linux__ -c midlayer.cpp -o midlayer.o
g++ -fpic -shared -DCAM_FRAME_480P -Wall -O2 -I/home/share/YSQfastfd/include -DPERF_STATISTICS -D_linux__ -o libaaid.so midlayer.o
make[1]: Leaving directory `/home/share/YSQfastfd/middle'
make[1]: Entering directory `/home/share/YSQfastfd/fcvlibtest'
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/share/YSQfastfd/include -DPERF_STATISTICS -D__linux__ libfcvtest.c -o libfcvtest -lm -lpthread `pkg-config --libs gtk+-3.0` -L/home/share/YSQfastfd/libfcv -loal -lm -lpthread `pkg-config --libs gtk+-3.0`
make[1]: Leaving directory `/home/share/YSQfastfd/fcvlibtest'
make[1]: Entering directory `/home/share/YSQfastfd/fddemo'
gcc -DCAM_FRAME_480P `pkg-config --cflags gtk+-3.0` -Wall -O2 -I/home/share/YSQfastfd/include -DPERF_STATISTICS -D__linux__ ysqfddemo.c -o ysqfddemo -lm -lpthread `pkg-config --libs gtk+-3.0` -L/home/share/YSQfastfd/libfcv -loal -L/home/share/YSQfastfd/middle -laaid -L/home/share/YSQfastfd/3rdlibs -lysqfd64 -lm -lpthread `pkg-config --libs gtk+-3.0`
/usr/bin/ld: skipping incompatible /home/share/YSQfastfd/3rdlibs/libysqfd64.so when searching for -lysqfd64
/usr/bin/ld: cannot find -lysqfd64
collect2: error: ld returned 1 exit status
make[1]: *** [ysqfddemo] Error 1
make[1]: Leaving directory `/home/share/YSQfastfd/fddemo'
make: *** [apps] Error 2`

我是在PC上编译，PC上的系统是Ubuntu14.04。我本来希望在ubuntu14上交叉编译，在R16上测试下您的库，但是没有成功，希望您解答下我下面的疑问，谢谢！
如果您有详细的操作步骤可以给一份我么？再次感谢您看我的邮件，谢谢！

文档中描述的评估需要准备的的环境：
32位 ARM或64位ARM硬件单板
USB 摄像头 （支持YUYV格式）
运行于硬件环境的ubuntu 16.04操作系统
Q1： 请问您这里的运行的16.04是用于编译的PC机上位机系统吧？

Platform preparation :
ARM32 platform hardware board
Ubuntu 16.04 with GTK3 library
Q2：这个是64位还是32位？是板载系统还是PC上的系统？
USB camera (480P/720P), YUYV
Build

Check the gtk+ devel library is installed
sudo apt install build-essential vim-gtk libgtk-3-0 libgtk-3-dev libegl1-mesa-dev
Q3： 这个命令是在上位机操作系统上进行安装，还是在板载系统上进行安装？
Build the runtime shared libraries

cd YSQfastfd
make -j4

fddemo/ysqfddemo
Q4：这个是在R40板子上编译在板子上运行?
makefile.mk文件：
CC = $(PREFIX)gcc
CXX = $(PREFIX)g++
AR = $(PREFIX)ar

# ARMv8 (arm64) enable, comment it if on arm32
ONARM64 = 1

Q5: PREFIX这个参数设置为arm-linux-gnueabihf-么？R40的话，ONARM64=0 吧？

**Comment by zyc737347123** [comment]
编译和运行都是在版载系统上执行的
r40的话，ONARM64=0
